[theme]
primaryColor = "#d4ac0d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f3f4"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
